### ISSUE TITLE
npm start fails on windows 10

### ISSUE THREAD

**Issue by third-bank-of-the-river** [leftstick/angular2-memory-game#1]
on windows 10 it fails: 
c:\projects\angular2\angular2-memory-game>npm start

`
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (c:\projects\angular2\angular2-memory-game\webpack.config.js:2:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-memory-game@1.0.0 start: `webpack-dev-server --hot --inline`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-memory-game@1.0.0 start script 'webpack-dev-server --hot --inline'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-memory-game package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --hot --inline
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-memory-game
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-memory-game
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\projects\angular2\angular2-memory-game\npm-debug.log
`

**Comment by leftstick** [comment]
What version of node you are using?

**Comment by third-bank-of-the-river** [comment]
npm ERR! node v5.8.0
npm ERR! npm v3.7.3

npm-debug.log:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.7.3
3 info using node@v5.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-memory-game@1.0.0~prestart: angular2-memory-game@1.0.0
6 silly lifecycle angular2-memory-game@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-memory-game@1.0.0~start: angular2-memory-game@1.0.0
8 verbose lifecycle angular2-memory-game@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-memory-game@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;c:\projects\angular2\angular2-memory-game\node_modules\.bin;C:\Program Files\nodejs;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Docker\Docker\Resources\bin;C:\ProgramData\Oracle\Java\javapath;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\TortoiseHg\;C:\Program Files (x86)\EaseUS\Todo Backup\bin;C:\Program Files (x86)\Calibre2\;C:\Program Files (x86)\Smart Projects\IsoBuster;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\HashiCorp\Vagrant\bin;C:\Program Files\Git\cmd;C:\ProgramData\Oracle\Java\javapath;C:\oraclexe\app\oracle\product\11.2.0\server\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\TortoiseHg\;C:\Program Files (x86)\EaseUS\Todo Backup\bin;C:\Program Files (x86)\Calibre2\;C:\Program Files (x86)\Smart Projects\IsoBuster;C:\Program Files (x86)\GNU\GnuPG\pub;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;c:\Java\jdk1.8.0_91\bin;c:\maven\apache-maven-3.1.1\bin;c:\Program Files\sqlite3\sqlite-tools-win32-x86-3100200;C:\Users\Elitebook\AppData\Roaming\npm;c:\Users\Elitebook\AppData\Roaming\npm;c:\gradle\gradle-2.13\bin;C:\Python27;C:\Python27\Scripts;C:\Users\Elitebook\AppData\Local\Microsoft\WindowsApps;c:\Program Files\Git\usr\bin\;c:\apache-ant-1.9.7\bin;C:\Program Files (x86)\EaseUS\Todo Backup\bin\x64\
10 verbose lifecycle angular2-memory-game@1.0.0~start: CWD: c:\projects\angular2\angular2-memory-game
11 silly lifecycle angular2-memory-game@1.0.0~start: Args: [ '/d /s /c', 'webpack-dev-server --hot --inline' ]
12 silly lifecycle angular2-memory-game@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2-memory-game@1.0.0~start: Failed to exec start script
14 verbose stack Error: angular2-memory-game@1.0.0 start: `webpack-dev-server --hot --inline`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at EventEmitter.emit (events.js:185:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:100:13)
14 verbose stack     at ChildProcess.emit (events.js:185:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-memory-game@1.0.0
16 verbose cwd c:\projects\angular2\angular2-memory-game
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v5.8.0
20 error npm  v3.7.3
21 error code ELIFECYCLE
22 error angular2-memory-game@1.0.0 start: `webpack-dev-server --hot --inline`
22 error Exit status 1
23 error Failed at the angular2-memory-game@1.0.0 start script 'webpack-dev-server --hot --inline'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-memory-game package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server --hot --inline
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-memory-game
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-memory-game
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by leftstick** [comment]
Can you upgrade node to >7.0？ I think there are some features i used not supportted with 5.8.0
