### ISSUE TITLE
GPL or MIT License?

### ISSUE THREAD

**Issue by EWBears** [leftstick/angular2-memory-game#3]
Hello Howard,

This is a nice looking memory game but I'm a little confused as to whether it is GPLv3 licensed or MIT licensed.  The actual license text is obviously GPLv3 but the package.json specifics MIT license and so does the readme.md. 

If you could clarify which license that this project uses it would be very helpful.  Thanks!

**Comment by leftstick** [comment]
It should be GPL, Thanks for your question, it was updated
